const APP_ACTIVITY_LOG_ACTIONS = new Set(['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'UPDATE']);

const RESET_TOKEN_TTL_MINUTES = 10;
const RESET_TOKEN_TTL_MS = RESET_TOKEN_TTL_MINUTES * 60 * 1000;

const EMAIL_CHANGE_TOKEN_TTL_MS = 48 * 60 * 60 * 1000;

module.exports = {
    APP_ACTIVITY_LOG_ACTIONS,
    RESET_TOKEN_TTL_MINUTES,
    RESET_TOKEN_TTL_MS,
    EMAIL_CHANGE_TOKEN_TTL_MS
};
